trigger:
- master

stages:
- stage: Build
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: 'Build_Job'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        version: '6.0.x'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration) -r $(BuildArchitecture) --self-contained true'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) -r $(BuildArchitecture) --self-contained true --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'FWAStatsJobCore'

- stage: Deploy
  jobs:
  - deployment: 'Deploy_Job'
    environment:
      name: FwaStats
      resourceType: VirtualMachine
    workspace:
      clean: true
    strategy:
      runOnce:
        deploy:
          steps:
          - task: ExtractFiles@1
            displayName: 'Extract files'
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/FWAStatsJobCore/*.zip'
              destinationFolder: '$(DestinationFolder)'
              cleanDestinationFolder: false
              overwriteExistingFiles: true
            